name: Compile Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ "1.10", "1.11" ]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Ohh it's a setup, it's a setup...
      run: |
        SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
        echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV                  
        echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV           
        echo "INCLUDE_PATH=$SOURCEMOD_PATH/include" >> $GITHUB_ENV   
        TOOLS_PATH=$GITHUB_WORKSPACE/tools                                    
        echo "TOOLS_PATH=$TOOLS_PATH" >> $GITHUB_ENV
        
    - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
      uses: rumblefrog/setup-sp@master
      with:
        version: ${{ matrix.sm-version }}

    - name: My anaconda don't...
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Go fetch! Good Doggo!
      run: |
        wget https://raw.githubusercontent.com/Impact123/AutoExecConfig/development/autoexecconfig.inc -P $INCLUDE_PATH
        wget https://raw.githubusercontent.com/c0rp3n/colorlib-sm/master/addons/sourcemod/scripting/include/colorlib.inc -P $INCLUDE_PATH
        git clone https://github.com/c0rp3n/colorlib-gen.git $TOOLS_PATH/gen

    - name: Taste the RAINBOW!
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        cd $TOOLS_PATH/gen/
        pip install -r ./requirements.txt
        python3 ./setup.py install
        colorlib_gen -re --config "$TOOLS_PATH/colors.yaml" "$INCLUDE_PATH/colorlib_map.inc"
        
    - name: Compile!
      run: |
        echo -e "\nCompiling ..."
        spcomp -w234 -O2 -v2 -i $INCLUDE_PATH mapchooser.sp
        spcomp -w234 -O2 -v2 -i $INCLUDE_PATH nominations.sp
        spcomp -w234 -O2 -v2 -i $INCLUDE_PATH rockthevote.sp
        spcomp -w234 -O2 -v2 -i $INCLUDE_PATH voteextend.sp
      working-directory: ${{ env.SCRIPTS_PATH }}/
        
